git:
  depth: 1

language: c
compiler: gcc
os: linux
dist: trusty
sudo: require

install:
  - autoreconf -W portability -visf

before_script:
  - ./test/ci/setup.sh

script:
  - ./test/ci/build.sh

env:
  matrix:
    - KEEPALIVED_CONFIG_ARGS=""
    - KEEPALIVED_CONFIG_ARGS="--enable-snmp --enable-snmp-rfc --enable-json"
    - KEEPALIVED_CONFIG_ARGS="--enable-sha1 --enable-dbus --disable-dynamic-linking --disable-fwmark --disable-lvs-syncd"
    - KEEPALIVED_CONFIG_ARGS="--enable-dynamic-linking --disable-vrrp-auth"
    - KEEPALIVED_CONFIG_ARGS="--disable-libiptc --disable-libipset --disable-libnl"
    - KEEPALIVED_CONFIG_ARGS="--enable-conversion-checks --enable-stacktrace --enable-mem-check --enable-mem-check-log --disable-lvs-64bit-stats"
    - KEEPALIVED_CONFIG_ARGS="--disable-lvs --enable-snmp --enable-snmp-rfc --enable-json --enable-sha1 --enable-dbus
    - KEEPALIVED_CONFIG_ARGS="--disable-vrrp --enable-snmp-checker --enable-json --enable-sha1 --enable-dbus"
