name: keepalived
version: '1.3.2'
summary: High availability VRRP and load-balancing for Linux
description: |
  Keepalived is routing software to provide simple and robust loadbalancing
  and high-availability to Linux based infrastructures.  The loadbalancing
  framework relies on the well-known Linux Virtual Server (IPVS) kernel
  module providing Layer4 loadbalancing. High-availability is achieved with
  the VRRP protocol.

grade: stable
confinement: classic

apps:
  keepalived:
    daemon: forking
    command: sbin/keepalived

parts:
  keepalived:
    # See 'snapcraft plugins'
    plugin: autotools
    source: .
